jupyterhub:
  nameOverride: binderhub-dev
  fullnameOverride: binderhub-dev
  ingress:
    hosts:
    - dev.binder.bioimagearchive.org
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/proxy-body-size: 2m
config:
  BinderHub:
    hub_url: http://dev.binder.bioimagearchive.org/jupyter/

ingress:
  enabled: true
  hosts:
  - dev.binder.bioimagearchive.org
  tls:
  - secretName: binder-bioimagearchive-org-cert
    hosts:
    - dev.binder.bioimagearchive.org

