jupyterhub:
  nameOverride: binder-dev
  fullnameOverride: binder-dev
  ingress:
    hosts:
      - ""
      - localhost
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/proxy-body-size: 2m
config:
  BinderHub:
    hub_url: https://localhost/jupyter

ingress:
  enabled: true
  hosts:
    - ""
    - localhost
  tls:
  - secretName: 
    hosts:
    # - ""


