apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: gitlab-runner
rules:
# Default in gitlab-runner helm chart is insufficent
#- apiGroups: [""]
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
