nameOverride: "daskhub-dev"
fullnameOverride: "daskhub-dev"

jupyterhub:

  ingress:
    enabled: true
    hosts:
    - dev.login.binder.bioimagearchive.org
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/proxy-body-size: 2m
    tls:
    - secretName: dev-login-binder-bioimagearchive-org-cert
      hosts:
      - dev.login.binder.bioimagearchive.org