

jupyterhub:

  ingress:
    enabled: true
    hosts:
    - dev.login.binder.bioimagearchive.org
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/proxy-body-size: 2m


