# PVC for JupyterHub shared scratch space
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jupyterhub-sharedscratch-rw
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ .Values.storage.className }}
  resources:
    requests:
      storage: {{ .Values.storage.requestSize }}
