variables:
  SSL_CERT_DIR: ''
  # DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ''

stages:
  - debug
  - setup
  - staging
  - production

debug:
  stage: debug
  script:
    - export
    
setup:
  stage: setup
  image: docker
  services:
  - name: docker:19.03.0-dind
  script:
    - docker login "$CI_REGISTRY" -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" 


staging:
  stage: staging
  image: praqma/helmsman:v3.5.1
  script:
    - helmsman --apply --debug --group staging -f helmsman_k8s_settings.yaml -f helmsman.yaml -f helmsman-staging.yaml
  # except:
  # - master

# production:
#   stage: production
#   script:
#     - helmsman --apply --debug --group production -f helmsman.yaml helmsman-production.yaml
#   only:
#   - production
