image: docker
services:
  - docker:19.03.0-dind

stages:
  - setup
  - staging
  - production

setup:
  image: praqma/helmsman:v3.5.1
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - helm list

staging:
  stage: staging
  script:
    - helmsman --apply --debug --group staging -f helmsman.yaml helmsman-staging.yaml
  # except:
  # - master

# production:
#   stage: production
#   script:
#     - helmsman --apply --debug --group production -f helmsman.yaml helmsman-production.yaml
#   only:
#   - production
