default:
  image: praqma/helmsman:v3.5.1

stages:
  - staging
  - production

# before_script:
#   - helm version || true
#   - helm list || true
before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

staging:
  stage: staging
  script:
    - helmsman --apply --debug --group staging -f helmsman.yaml helmsman-staging.yaml
  except:
  - master

# production:
#   stage: production
#   script:
#     - helmsman --apply --debug --group production -f helmsman.yaml helmsman-production.yaml
#   only:
#   - production
