######################################################################
# Common settings

image: imagedata/kube-helm-docker:0.1.0

stages:
  - staging
  - approval
  - production

variables:
  # Don't use default since we need extra permissions for deployment
  KUBERNETES_SERVICE_ACCOUNT_OVERWRITE: gitlab-runner

before_script:
  - helm list


######################################################################
# Jobs
# Deployment logs are public so ensure all you never echo any secret
# variables


# Staging is run automatically when master is updated
# Deletes an existing deployment before installing
staging:
  stage: staging
  before_script:
    - helm list
    # Disable delete for now to see if it fixes an redeployment problem
    #- helmfile --hide-args --selector application=staging delete || true
  script:
    - sh gitlab-ci/deploy.sh
    # TODO: Check we can run singleuser servers
  environment:
    name: staging-staging
    url: https://idr-analysis.openmicroscopy.org/staging
  only:
  - master

# Production requires a manual trigger
approval:
  stage: approval
  script:
    - echo Manual approval required
  allow_failure: false
  only:
  - master
  when: manual

# Training (no login) production
# Upgrades if already installed
training:
  stage: production
  script:
    - sh gitlab-ci/deploy.sh
    # TODO: Check we can run singleuser servers
  environment:
    name: production-training
    url: https://idr-analysis.openmicroscopy.org/training
  only:
  - master

# ITR Public (no login) production
# Upgrades if already installed
deploy_itr_public:
  stage: production
  script:
    - sh gitlab-ci/deploy.sh
    # TODO: Check we can run singleuser servers
  environment:
    name: production-itr-public
    url: https://idr-analysis.openmicroscopy.org/itr-public
  only:
  - master

# Public (no login) production
# Upgrades if already installed
deploy_public:
  stage: production
  script:
    - sh gitlab-ci/deploy.sh
    # TODO: Check we can run singleuser servers
  environment:
    name: production-public
    url: https://idr-analysis.openmicroscopy.org/public
  only:
  - master

# VAE production
# Upgrades if already installed
deploy_vae:
  stage: production
  script:
    - sh gitlab-ci/deploy.sh
    # TODO: Check we can run singleuser servers
  environment:
    name: production-vae
    url: https://idr-analysis.openmicroscopy.org/vae
  only:
  - master

# VAE AAI production
# Upgrades if already installed
deploy_vaeaai:
  stage: production
  script:
    - sh gitlab-ci/deploy.sh
    # TODO: Check we can run singleuser servers
  environment:
    name: production-vae-aai
    url: https://idr-analysis.openmicroscopy.org/vae
  only:
  - master

# Website
# Upgrades if already installed
deploy_website:
  stage: production
  script:
    - helmfile --hide-args --selector application=website sync --args '--wait --timeout=300'
  environment:
    name: production-website
    url: https://idr-analysis.openmicroscopy.org/
  only:
  - master

# Monitoring
# Upgrades if already installed
deploy_monitoring:
  stage: production
  script:
    - helmfile --hide-args --selector application=monitoring sync --args '--wait --timeout=300'
  environment:
    name: production-monitoring
    url: https://idr-analysis.openmicroscopy.org/grafana
  only:
  - master
