# .readthedocs.yaml
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.8"

# Tell RTD to use MkDocs and point at your config
mkdocs:
  configuration: mkdocs.yaml

# (Optional) if you need Python dependencies, e.g. mkdocs-material
python:
  install:
    - requirements: requirements.txt

# (Optional) target formats
formats:
  - htmlzip
