helmDefaults:
  wait: true
  timeout: 1200
  force: true

# TODO: Common configuration
# Needs Helmfile 0.43.2 but will reduce duplication
# templates:
#   default_jupyterhub: &default_jupyterhub
#     chart: jupyterhub/jupyterhub
#     # Wed, 23 Jan 2019 15:37:58 +0000
#     version: 0.8-d470e4f

repositories:
  - name: jupyterhub
    url: https://jupyterhub.github.io/helm-chart/

releases:


######################################################################
# JupyterHub staging

  - name: jupyterhub-staging
    chart: jupyterhub/jupyterhub
    # Wed, 23 Jan 2019 15:37:58 +0000
    version: 0.8-d470e4f
    namespace: jupyterhub-staging
    labels:
      deployment: staging
      application: staging
    values:
      - jupyterhub-config.yaml
    set:
      - name: proxy.secretToken
        value: {{ requiredEnv "SECRET_JUPYTERHUB_PROXY_TOKEN" }}
      - name: singleuser.extraEnv.IDR_PASSWORD
        value: {{ requiredEnv "SECRET_IDR_PASSWORD" }}


######################################################################
# JupyterHub training

  - name: jupyterhub-training
    chart: jupyterhub/jupyterhub
    # Wed, 23 Jan 2019 15:37:58 +0000
    version: 0.8-d470e4f
    namespace: jupyterhub-training
    labels:
      deployment: production
      application: training
    values:
      - jupyterhub-config.yaml
      - jupyterhub-training.yaml
    set:
      - name: proxy.secretToken
        value: {{ requiredEnv "SECRET_JUPYTERHUB_PROXY_TOKEN" }}


######################################################################
# JupyterHub ITR production

  - name: jupyterhub-itr-public
    chart: jupyterhub/jupyterhub
    # Wed, 23 Jan 2019 15:37:58 +0000
    version: 0.8-d470e4f
    namespace: jupyterhub-itr-public
    labels:
      deployment: production
      application: itr-public
    values:
      - jupyterhub-config.yaml
      - jupyterhub-itr-public.yaml
    set:
      - name: proxy.secretToken
        value: {{ requiredEnv "SECRET_JUPYTERHUB_PROXY_TOKEN" }}
      - name: singleuser.extraEnv.IDR_PASSWORD
        value: {{ requiredEnv "SECRET_IDR_PASSWORD" }}


######################################################################
# JupyterHub production

  - name: jupyterhub-public
    chart: jupyterhub/jupyterhub
    # Wed, 23 Jan 2019 15:37:58 +0000
    version: 0.8-d470e4f
    namespace: jupyterhub-public
    labels:
      deployment: production
      application: public
    values:
      - jupyterhub-config.yaml
      - jupyterhub-public.yaml
    set:
      - name: proxy.secretToken
        value: {{ requiredEnv "SECRET_JUPYTERHUB_PROXY_TOKEN" }}
      - name: singleuser.extraEnv.IDR_PASSWORD
        value: {{ requiredEnv "SECRET_IDR_PASSWORD" }}

  - name: jupyterhub-vae
    chart: jupyterhub/jupyterhub
    # Wed, 23 Jan 2019 15:37:58 +0000
    version: 0.8-d470e4f
    namespace: jupyterhub-vae
    labels:
      deployment: production
      application: vae
    values:
      - jupyterhub-config.yaml
      - jupyterhub-vae.yaml
    set:
      - name: proxy.secretToken
        value: {{ requiredEnv "SECRET_JUPYTERHUB_PROXY_TOKEN" }}
      - name: singleuser.extraEnv.IDR_PASSWORD
        value: {{ requiredEnv "SECRET_IDR_PASSWORD" }}
      - name: auth.github.clientId
        value: {{ requiredEnv "SECRET_GITHUB_CLIENTID" }}
      - name: auth.github.clientSecret
        value: {{ requiredEnv "SECRET_GITHUB_CLIENTSECRET" }}

  - name: jupyterhub-vae-shared-storage
    namespace: jupyterhub-vae
    chart: ./charts/jupyterhub-shared-scratch
    labels:
      deployment: production
      application: vae
  - name: jupyterhub-vae-aai
    chart: jupyterhub/jupyterhub
    # Wed, 23 Jan 2019 15:37:58 +0000
    version: 0.8-d470e4f
    namespace: jupyterhub-vae-aai
    labels:
      deployment: production
      application: vae-aai
    values:
      - jupyterhub-config.yaml
      - jupyterhub-vae-aai.yaml
    set:
      - name: proxy.secretToken
        value: {{ requiredEnv "SECRET_JUPYTERHUB_PROXY_TOKEN" }}
      - name: singleuser.extraEnv.IDR_PASSWORD
        value: {{ requiredEnv "SECRET_IDR_PASSWORD" }}
      - name: hub.extraEnv.OAUTH_CLIENT_ID
        value: {{ requiredEnv "SECRET_AAI_CLIENTID" }}
      - name: hub.extraEnv.OAUTH_CLIENT_SECRET
        value: {{ requiredEnv "SECRET_AAI_CLIENTSECRET" }}



######################################################################
# Website

  - name: idr-analysis-website
    namespace: idr-analysis-website
    chart: ./charts/idr-analysis-website
    labels:
      deployment: production
      application: website


######################################################################
# Monitoring

  - name: prometheus-auth
    namespace: monitoring
    chart: ./charts/kubernetes-secret
    labels:
      deployment: production
      application: monitoring
    set:
      - name: data.auth
        value: {{ requiredEnv "SECRET_PROMETHEUS_AUTH_HTPASSWD" }}
    # To create this value:
    # htpasswd -bc auth username password
    # base64 auth

  - name: prometheus
    namespace: monitoring
    chart: stable/prometheus
    version: 6.3.3
    labels:
      deployment: production
      application: monitoring
    values:
      - prometheus.yaml

  - name: grafana
    namespace: monitoring
    chart: stable/grafana
    version: 1.3.0
    labels:
      deployment: production
      application: monitoring
    values:
      - grafana.yaml
    set:
      - name: env.GF_AUTH_GITHUB_CLIENT_ID
        value: {{ requiredEnv "SECRET_GRAFANA_GITHUB_CLIENTID" }}
      - name: env.GF_AUTH_GITHUB_CLIENT_SECRET
        value: {{ requiredEnv "SECRET_GRAFANA_GITHUB_SECRET" }}

    # To get the auto-generated Grafana admin password:
    # kubectl get secret --namespace monitoring grafana -o jsonpath="{.data.admin-password}" | base64 -d ; echo
