# Common configuration
RELEASE_COMMON: &RELEASE_COMMON
  chart: jupyterhub/jupyterhub
  # Tue, 01 May 2018 23:35:58 +0000
  version: v0.7-d617e0a

repositories:
  - name: jupyterhub
    url: https://jupyterhub.github.io/helm-chart/

releases:


######################################################################
# JupyterHub staging

  - <<: *RELEASE_COMMON
    name: jupyterhub-staging
    namespace: jupyterhub-staging
    labels:
      deployment: staging
      application: staging
    values:
      - jupyterhub-config.yaml
    set:
      - name: proxy.secretToken
        value: "{{ env \"SECRET_JUPYTERHUB_PROXY_TOKEN\" }}"
      - name: singleuser.extraEnv.IDR_PASSWORD
        value: "{{ env \"SECRET_IDR_PASSWORD\" }}"


######################################################################
# JupyterHub training
# This is deployed as part of staging for now

  - <<: *RELEASE_COMMON
    name: jupyterhub-training
    namespace: jupyterhub-training
    labels:
      deployment: staging
      application: training
    values:
      - jupyterhub-config.yaml
      - jupyterhub-training.yaml
    set:
      - name: proxy.secretToken
        value: "{{ env \"SECRET_JUPYTERHUB_PROXY_TOKEN\" }}"


######################################################################
# JupyterHub ITR production

  # Note this is newer than the version in RELEASE_COMMON
  - chart: jupyterhub/jupyterhub
    # Tue, 07 Aug 2018 19:55:47 +0000
    version: v0.7-15e87d6
    name: jupyterhub-itr-public
    namespace: jupyterhub-itr-public
    labels:
      deployment: production
      application: itr-public
    values:
      - jupyterhub-config.yaml
      - jupyterhub-itr-public.yaml
    set:
      - name: proxy.secretToken
        value: "{{ env \"SECRET_JUPYTERHUB_PROXY_TOKEN\" }}"
      - name: singleuser.extraEnv.IDR_PASSWORD
        value: "{{ env \"SECRET_IDR_PASSWORD\" }}"


######################################################################
# JupyterHub production

  - <<: *RELEASE_COMMON
    name: jupyterhub-public
    namespace: jupyterhub-public
    labels:
      deployment: production
      application: public
    values:
      - jupyterhub-config.yaml
      - jupyterhub-public.yaml
    set:
      - name: proxy.secretToken
        value: "{{ env \"SECRET_JUPYTERHUB_PROXY_TOKEN\" }}"
      - name: singleuser.extraEnv.IDR_PASSWORD
        value: "{{ env \"SECRET_IDR_PASSWORD\" }}"

  - <<: *RELEASE_COMMON
    name: jupyterhub-vae
    namespace: jupyterhub-vae
    labels:
      deployment: production
      application: vae
    values:
      - jupyterhub-config.yaml
      - jupyterhub-vae.yaml
    set:
      - name: proxy.secretToken
        value: "{{ env \"SECRET_JUPYTERHUB_PROXY_TOKEN\" }}"
      - name: singleuser.extraEnv.IDR_PASSWORD
        value: "{{ env \"SECRET_IDR_PASSWORD\" }}"
      - name: auth.github.clientId
        value: "{{ env \"SECRET_GITHUB_CLIENTID\" }}"
      - name: auth.github.clientSecret
        value: "{{ env \"SECRET_GITHUB_CLIENTSECRET\" }}"

  - name: jupyterhub-vae-shared-storage
    namespace: jupyterhub-vae
    chart: ./charts/jupyterhub-shared-scratch
    labels:
      deployment: production
      application: vae

  - <<: *RELEASE_COMMON
    name: jupyterhub-vae-aai
    namespace: jupyterhub-vae-aai
    labels:
      deployment: production
      application: vae-aai
    values:
      - jupyterhub-config.yaml
      - jupyterhub-vae-aai.yaml
    set:
      - name: proxy.secretToken
        value: "{{ env \"SECRET_JUPYTERHUB_PROXY_TOKEN\" }}"
      - name: singleuser.extraEnv.IDR_PASSWORD
        value: "{{ env \"SECRET_IDR_PASSWORD\" }}"
      - name: hub.extraEnv.OAUTH_CLIENT_ID
        value: "{{ env \"SECRET_AAI_CLIENTID\" }}"
      - name: hub.extraEnv.OAUTH_CLIENT_SECRET
        value: "{{ env \"SECRET_AAI_CLIENTSECRET\" }}"


######################################################################
# Website

  - name: idr-analysis-website
    namespace: idr-analysis-website
    chart: ./charts/idr-analysis-website
    labels:
      deployment: production
      application: website


######################################################################
# Monitoring

  - name: prometheus-auth
    namespace: monitoring
    chart: ./charts/kubernetes-secret
    labels:
      deployment: production
      application: monitoring
    set:
      - name: data.auth
        value: "{{ env \"SECRET_PROMETHEUS_AUTH_HTPASSWD\" }}"
    # To create this value:
    # htpasswd -bc auth username password
    # base64 auth

  - name: prometheus
    namespace: monitoring
    chart: stable/prometheus
    version: 6.3.3
    labels:
      deployment: production
      application: monitoring
    values:
      - prometheus.yaml

  - name: grafana
    namespace: monitoring
    chart: stable/grafana
    version: 1.3.0
    labels:
      deployment: production
      application: monitoring
    values:
      - grafana.yaml
    set:
      - name: env.GF_AUTH_GITHUB_CLIENT_ID
        value: "{{ env \"SECRET_GRAFANA_GITHUB_CLIENTID\" }}"
      - name: env.GF_AUTH_GITHUB_CLIENT_SECRET
        value: "{{ env \"SECRET_GRAFANA_GITHUB_SECRET\" }}"

    # To get the auto-generated Grafana admin password:
    # kubectl get secret --namespace monitoring grafana -o jsonpath="{.data.admin-password}" | base64 -d ; echo
