site_name: "BioImageArchive Binder"
site_url: "https://binder.bioimagearchive.org/"
nav:
  - 'index.md'
  - 'user_guide.md'
  # - 'jupyter.md'
  # - 'kubeflow.md'
  - 'deployment.md'
  # - 'setup.md'
theme: readthedocs
