# Based on
# https://github.com/jupyterhub/mybinder.org-deploy/blob/d53420cdbc94d2148018594d33cd35810bbffbf1/mybinder/values.yaml#L213
nodeExporter:
  updateStrategy:
    type: RollingUpdate
alertmanager:
  enabled: false
pushgateway:
  enabled: false
rbac:
  create: true
server:
  baseURL: https://idr-analysis.openmicroscopy.org/prometheus
  extraArgs:
    # https://github.com/prometheus/prometheus/issues/2813#issuecomment-344359402
    web.route-prefix: /
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/rewrite-target: /
      nginx.ingress.kubernetes.io/add-base-url: "true"
      nginx.ingress.kubernetes.io/auth-type: basic
      nginx.ingress.kubernetes.io/auth-secret: prometheus-auth-kubernetes-secret
      nginx.ingress.kubernetes.io/auth-realm: Prometheus
    hosts:
    # Requires Helm 2.8.2 due to a bug(?)
    - idr-analysis.openmicroscopy.org/prometheus
    tls:
    - hosts:
      - idr-analysis.openmicroscopy.org
  persistentVolume:
    enabled: true
    size: 10G
    storageClass: gluster
  retention: 21d
