config:
  BinderHub:
    auth_enabled: false
    hub_url: https://binder.bioimagearchive.org/binderhub/

jupyterhub:
  hub:
    baseUrl: /binderhub
    config:
      GitHubOAuthenticator:
        oauth_callback_url: https://binder.bioimagearchive.org/binderhub/hub/oauth_callback
  ingress:
    enabled: true
    hosts:
      - binder.bioimagearchive.org
  custom:
    binderauth_enabled: false

ingress:
  enabled: true
  hosts:
    - "binder.bioimagearchive.org"
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    cert-manager.k8s.io/acme-challenge-type: http01
    cert-manager.io/cluster-issuer: letsencrypt-production
    # https:
    #   enabled: true
    #   type: nginx
  tls:
    - secretName: binder-bioimagearchive-org-cert
      hosts:
        - binder.bioimagearchive.org