config:
  BinderHub:
    hub_url: http://binder.bioimagearchive.org/binderhub/

jupyterhub:
  hub:
    baseUrl: /binderhub
  ingress:
    enabled: true
    hosts:
      - binder.bioimagearchive.org

ingress:
  enabled: true
  hosts:
    - "binder.bioimagearchive.org"