config:
  BinderHub:
    hub_url: beta.binder.bioimagearchive.org/binderhub/
    banner_message: |
      <div style="text-align: center;">Beta service with more RAM and CPU  (no DIND atm)</div>
jupyterhub:
  hub:
    baseUrl: /binderhub
  ingress:
    enabled: true
    hosts:
      - beta.binder.bioimagearchive.org

ingress:
  enabled: true
  hosts:
    - "beta.binder.bioimagearchive.org"
  tls:
  annotations:
    kubernetes.io/ingress.class: nginx

dind:
  enabled: true