jupyterhub:
  custom:
    binderauth_enabled: false
  hub:
    baseUrl: /jhub
  ingress:
    enabled: true
    hosts:
      - gpu.binder.bioimagearchive.org
  singleuser:
  profileList:
    - display_name: "GPU Server"
      description: "Spawns a notebook server with access to a GPU"
      kubespawner_override:
        extra_resource_limits:
          nvidia.com/gpu: "1"
    - display_name: "No GPU"
      description: "Spawns a notebook server with access to a GPU"

config:
  BinderHub:
    auth_enabled: false
    hub_url: https://gpu.binder.bioimagearchive.org/jhub
    banner_message: |
      <div style="text-align: center;">Beta service with more RAM and CPU and GPU Support </div>


ingress:
  enabled: true
  hosts:
    - "gpu.binder.bioimagearchive.org"
  tls:
  annotations:
    kubernetes.io/ingress.class: nginx
    
dind:
  enabled: true

service:
  type: ClusterIP