apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "nfs-bs-ftp-pvc-jupyterhub-staging"
spec:
  storageClassName: nfs
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 10Gi
  volumeName: "nfs-bs-ftp-pv"
