config:
  BinderHub:
    hub_url: https://staging.ctr26.duckdns.org/jhub/

jupyterhub:
  hub:
    baseUrl: /jhub
  ingress:
    enabled: true
    hosts:
      - staging.binder.bioimagearchive.org

ingress:
  enabled: true
  hosts:
    - "staging.ctr26.duckdns.org"
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    cert-manager.k8s.io/acme-challenge-type: http01
    cert-manager.io/cluster-issuer: letsencrypt-production
  tls:
    - secretName: binder-bioimagearchive-org-cert
      hosts:
        - "staging.ctr26.duckdns.org"

service:
  type: ClusterIP


dind:
  hostLibDir: /var/lib/dind/staging
  hostSocketDir: /var/run/dind/staging