config:
  BinderHub:
    hub_url: http://staging.binder.bioimagearchive.org/binderhub/

jupyterhub:
  hub:
    baseUrl: /binderhub
  ingress:
    enabled: true
    hosts:
      - staging.binder.bioimagearchive.org

ingress:
  enabled: true
  hosts:
    - "staging.binder.bioimagearchive.org"
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    cert-manager.k8s.io/acme-challenge-type: http01
    cert-manager.io/cluster-issuer: letsencrypt-production
    https:
      enabled: true
      type: nginx
  tls:
    - secretName: binder-bioimagearchive-org-cert
      hosts:
service:
  type: ClusterIP


dind:
  hostLibDir: /var/lib/dind/staging
  hostSocketDir: /var/run/dind/staging