config:
  BinderHub:
    hub_url: http://staging.beta.binder.bioimagearchive.org/binderhub/
    banner_message: |
      <div style="text-align: center;">Beta service with more RAM and CPU</div>
jupyterhub:
  hub:
    baseUrl: /binderhub
  ingress:
    enabled: true
    hosts:
      - staging.beta.binder.bioimagearchive.org

ingress:
  enabled: true
  hosts:
    - "staging.beta.binder.bioimagearchive.org"