apiVersion: v1
kind: Secret
metadata:
  name: {{ template "kubernetes-secret.fullname" . }}
  labels:
    app: {{ template "kubernetes-secret.name" . }}
    chart: {{ template "kubernetes-secret.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  {{- range $key, $value := .Values.data }}
    {{ $key }}: {{ $value }}
  {{- end }}
