global:
  name: consul
  datacenter: embassy
  # tls:
  #   enabled: true
  #   verify: false
  #   httpsOnly: true


connectInject:
  enabled: true


 # Configure federation.
  federation:
    # If enabled, this datacenter will be federation-capable. Only federation
    # via mesh gateways is supported.
    # Mesh gateways and servers will be configured to allow federation.
    # Requires `global.tls.enabled`, `meshGateway.enabled` and `connectInject.enabled`
    # to be true. Requires Consul 1.8+.
    enabled: false
    createFederationSecret: true
    primaryDatacenter: embassy


    # If you are setting `global.federation.enabled` to true and are in a secondary datacenter,
    # set `k8sAuthMethodHost` to the address of the Kubernetes API server of the secondary datacenter.
    # This address must be reachable from the Consul servers in the primary datacenter.
    # This auth method will be used to provision ACL tokens for Consul components and is different
    # from the one used by the Consul Service Mesh.
    # Please refer to the [Kubernetes Auth Method documentation](https://developer.hashicorp.com/consul/docs/security/acl/auth-methods/kubernetes).
    #
    # You can retrieve this value from your `kubeconfig` by running:
    #
    # ```shell-session
    # $ kubectl config view \
    #   -o jsonpath="{.clusters[?(@.name=='<your cluster name>')].cluster.server}"
    # ```
    #
    # @type: string
    k8sAuthMethodHost: null