namespaces:
  prod:
    protected: true
  dev:
    protected: false
  cert-manager:
    protected: true
  ingress-nginx:
    protected: true
  nginx-ingress:
    protected: true
  docker-registry:
    protected: true
  tritoninferenceserver:
    protected: true
  monitoring:
    protected: true
  nvidia-device-plugin:
    protected: true
  gpu-operator:
    protected: true

apps:
  daskhub:
    namespace: "dev"
    group: "dev"
    name: "daskhub-dev"
    valuesFiles:
    - "../daskhub/values.yaml"
    - "../daskhub/dev.yaml"
  binderhub:
    namespace: "dev"
    group: "dev"
    name: "binderhub-dev"
    valuesFiles:
    - "../binderhub/values.yaml"
    - "../binderhub/dev.yaml"
  # cert-manager:
    # enabled: true
  # nvidia-gpu-operator:
    # enabled: true