namespaces:
  jupyterhub-sandbox-staging:
    protected: false
  jupyterhub-sandbox-production:
    protected: false
  jupyterhub-github-staging:
    protected: false
  jupyterhub-github-production:
    protected: false
  binderhub-staging:
    protected: false
  binderhub-production:
    protected: false
  persistent-binderhub-staging:
    protected: false
  persistent-binderhub-production:
    protected: false
  daskgateway-staging:
    protected: false
  daskgateway-production:
    protected: false
  binderhub-production-gpu:
    protected: false
  binderhub-staging-gpu:
    protected: false
  cert-manager:
    protected: false
  ingress-nginx:
    protected: false
