namespaces:
  jupyterhub-sandbox-staging:
    protected: false
  jupyterhub-sandbox-production:
    protected: true
  jupyterhub-github-staging:
    protected: false
  jupyterhub-github-production:
    protected: true
  binderhub-staging:
    protected: false
  binderhub-production:
    protected: true
  persistent-binderhub-staging:
    protected: false
  persistent-binderhub-production:
    protected: true
  binderhub-staging-gpu:
    protected: true
  binderhub-production-gpu:
    protected: true
  daskgateway-staging:
    protected: false
  daskgateway-production:
    protected: true
  cert-manager:
    protected: true
  ingress-nginx:
    protected: true
  nginx-ingress:
    protected: true
  trow:
    protected: true
  docker-registry:
    protected: true
  tritoninferenceserver:
    protected: true
  monitoring:
    protected: true
  nvidia-device-plugin:
    protected: true
