namespaces:
  jupyterhub-sandbox-staging:
    protected: false
  jupyterhub-sandbox-production:
    protected: true
  jupyterhub-github-staging:
    protected: false
  jupyterhub-github-production:
    protected: true
  binderhub-staging:
    protected: false
  binderhub-production:
    protected: true
  binderhub-staging-gpu:
    protected: true
  binderhub-production-gpu:
    protected: true
  daskgateway-staging:
    protected: false
  daskgateway-production:
    protected: true
