ingress:
  hosts:
    - minikube.local
    - ""
    - localhost
  tls:
    - hosts:
        - minikube.local
        - localhost
singleuser:
  storage:
    extraVolumes:
      - persistentVolumeClaim:
          claimName: nfs-bs-ftp-pv-jupyerhub-production
