apiVersion: v1
kind: PersistentVolume
metadata:
  name: biostudies-nfs
spec:
  storageClassName: nfs
  capacity:
    storage: 1Gi
  accessModes:
    - ReadOnlyMany
  mountOptions:
    - nfsvers=3
  nfs:
    # path: /tmp
    # server: 172.17.0.2
    # server: 10.35.105.251 # Change this!
    server: 10.35.198.252
    path: "/fg_biostudies/.adm/databases/prod/submission/ftp/"
    readOnly: true
  # claimRef:
  #   name: nfs-bs-ftp-pvc
# persistentVolumeReclaimPolicy:
#   Recycle
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: biostudies-nfs-pvc
spec:
  storageClassName: nfs
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi
  volumeName: biostudies-nfs
