
# Configuration for JupyterHub dev deployment
# Overridden in prod deployments
nameOverride: jupyter-dev
fullnameOverride: jupyter-dev

ingress:
  enabled: true
  hosts:
  - dev.login.binder.bioimagearchive.org

