server:
  baseURL: https://minikube.local/prometheus
  ingress:
    annotations:
      nginx.ingress.kubernetes.io/auth-type: null
      nginx.ingress.kubernetes.io/auth-secret: null
      nginx.ingress.kubernetes.io/auth-realm: null
    hosts:
    - minikube.local/prometheus
    tls:
    - hosts:
      - minikube.local
  persistentVolume:
    size: 100M
    storageClass:
