server:
  baseURL: https://localhost/prometheus
  ingress:
    annotations:
      nginx.ingress.kubernetes.io/auth-type: null
      nginx.ingress.kubernetes.io/auth-secret: null
      nginx.ingress.kubernetes.io/auth-realm: null
    hosts:
    - localhost/prometheus
    tls:
    - hosts:
      - localhost
  persistentVolume:
    size: 100M
    storageClass:
