name: binderhub-bump

on:
  workflow_dispatch:
  schedule:
    - cron: '16 3 * * *'

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: python -mpip install -r binderhub-bump/requirements.txt
      - run: |
          ./binderhub-bump/bump.py
          git diff
      - uses: peter-evans/create-pull-request@v3
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          branch: binderhub-bump
          title: "Bump BinderHub Helm Chart"
          body: |
            Bump BinderHub Helm Chart
          commit-message: |
            Bump BinderHub Helm Chart
